#include <stdint.h>

#define MODE_FISCHER 0
#define MODE_BRONSTEIN 1

#define OSCILLATOR_CALIBRATION 0x76

#define MAIN_TIME 30 * 1000L
// #define TIME_INCREMENT 30*1000L
#define INCREMENT_MODE MODE_FISCHER
#define RESET_DELAY 3000
